# permissions for end users to view dockernodeupdatetasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-inplace-updater
    app.kubernetes.io/managed-by: kustomize
  name: dockernodeupdatetask-viewer-role
rules:
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - dockernodeupdatetasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - dockernodeupdatetasks/status
  verbs:
  - get
