---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  - machines/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kubeadmcontrolplanes
  - kubeadmcontrolplanes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - dockernodeupdatetasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - dockernodeupdatetasks/finalizers
  verbs:
  - update
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - dockernodeupdatetasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - dockernodeupdatetasktemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - updatetasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - updatetasks/finalizers
  verbs:
  - update
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - updatetasks/status
  verbs:
  - get
  - patch
  - update
