---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - upgrade.extension.cluster.x-k8s.io
  resources:
  - upgradetasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upgrade.extension.cluster.x-k8s.io
  resources:
  - upgradetasks/finalizers
  verbs:
  - update
- apiGroups:
  - upgrade.extension.cluster.x-k8s.io
  resources:
  - upgradetasks/status
  verbs:
  - get
  - patch
  - update
