---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - upgrade.extension.cluster.x-k8s.io
  resources:
  - upgradetasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upgrade.extension.cluster.x-k8s.io
  resources:
  - upgradetasks/finalizers
  verbs:
  - update
- apiGroups:
  - upgrade.extension.cluster.x-k8s.io
  resources:
  - upgradetasks/status
  verbs:
  - get
  - patch
  - update
