# permissions for end users to view updatetasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: updatetask-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-inplace-updater
    app.kubernetes.io/part-of: cluster-api-inplace-updater
    app.kubernetes.io/managed-by: kustomize
  name: updatetask-viewer-role
rules:
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - updatetasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - update.extension.cluster.x-k8s.io
  resources:
  - updatetasks/status
  verbs:
  - get
