# permissions for end users to view upgradetasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: upgradetask-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-inplace-upgrader
    app.kubernetes.io/part-of: cluster-api-inplace-upgrader
    app.kubernetes.io/managed-by: kustomize
  name: upgradetask-viewer-role
rules:
- apiGroups:
  - upgrade.extension.cluster.x-k8s.io
  resources:
  - upgradetasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - upgrade.extension.cluster.x-k8s.io
  resources:
  - upgradetasks/status
  verbs:
  - get
