## Append samples of your project ##
resources:
- update_v1beta1_updatetask.yaml
- update_v1beta1_updatepolicy.yaml
- update_v1beta1_dockernodeupdatetask.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
