//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneExternalUpdateRequest) DeepCopyInto(out *ControlPlaneExternalUpdateRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	if in.ClusterRef != nil {
		in, out := &in.ClusterRef, &out.ClusterRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ControlPlaneRef != nil {
		in, out := &in.ControlPlaneRef, &out.ControlPlaneRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.MachinesRequireUpdate != nil {
		in, out := &in.MachinesRequireUpdate, &out.MachinesRequireUpdate
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	out.NewMachine = in.NewMachine
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneExternalUpdateRequest.
func (in *ControlPlaneExternalUpdateRequest) DeepCopy() *ControlPlaneExternalUpdateRequest {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneExternalUpdateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneExternalUpdateResponse) DeepCopyInto(out *ControlPlaneExternalUpdateResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneExternalUpdateResponse.
func (in *ControlPlaneExternalUpdateResponse) DeepCopy() *ControlPlaneExternalUpdateResponse {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneExternalUpdateResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeUpdateTask) DeepCopyInto(out *DockerNodeUpdateTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeUpdateTask.
func (in *DockerNodeUpdateTask) DeepCopy() *DockerNodeUpdateTask {
	if in == nil {
		return nil
	}
	out := new(DockerNodeUpdateTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerNodeUpdateTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeUpdateTaskList) DeepCopyInto(out *DockerNodeUpdateTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DockerNodeUpdateTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeUpdateTaskList.
func (in *DockerNodeUpdateTaskList) DeepCopy() *DockerNodeUpdateTaskList {
	if in == nil {
		return nil
	}
	out := new(DockerNodeUpdateTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerNodeUpdateTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeUpdateTaskSpec) DeepCopyInto(out *DockerNodeUpdateTaskSpec) {
	*out = *in
	out.NewMachineSpec = in.NewMachineSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeUpdateTaskSpec.
func (in *DockerNodeUpdateTaskSpec) DeepCopy() *DockerNodeUpdateTaskSpec {
	if in == nil {
		return nil
	}
	out := new(DockerNodeUpdateTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeUpdateTaskStatus) DeepCopyInto(out *DockerNodeUpdateTaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]apiv1beta1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeUpdateTaskStatus.
func (in *DockerNodeUpdateTaskStatus) DeepCopy() *DockerNodeUpdateTaskStatus {
	if in == nil {
		return nil
	}
	out := new(DockerNodeUpdateTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeUpdateTaskTemplate) DeepCopyInto(out *DockerNodeUpdateTaskTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeUpdateTaskTemplate.
func (in *DockerNodeUpdateTaskTemplate) DeepCopy() *DockerNodeUpdateTaskTemplate {
	if in == nil {
		return nil
	}
	out := new(DockerNodeUpdateTaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerNodeUpdateTaskTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeUpdateTaskTemplateList) DeepCopyInto(out *DockerNodeUpdateTaskTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DockerNodeUpdateTaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeUpdateTaskTemplateList.
func (in *DockerNodeUpdateTaskTemplateList) DeepCopy() *DockerNodeUpdateTaskTemplateList {
	if in == nil {
		return nil
	}
	out := new(DockerNodeUpdateTaskTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DockerNodeUpdateTaskTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeUpdateTaskTemplateResource) DeepCopyInto(out *DockerNodeUpdateTaskTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeUpdateTaskTemplateResource.
func (in *DockerNodeUpdateTaskTemplateResource) DeepCopy() *DockerNodeUpdateTaskTemplateResource {
	if in == nil {
		return nil
	}
	out := new(DockerNodeUpdateTaskTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerNodeUpdateTaskTemplateSpec) DeepCopyInto(out *DockerNodeUpdateTaskTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerNodeUpdateTaskTemplateSpec.
func (in *DockerNodeUpdateTaskTemplateSpec) DeepCopy() *DockerNodeUpdateTaskTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(DockerNodeUpdateTaskTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNodeUpdateTask) DeepCopyInto(out *FakeNodeUpdateTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNodeUpdateTask.
func (in *FakeNodeUpdateTask) DeepCopy() *FakeNodeUpdateTask {
	if in == nil {
		return nil
	}
	out := new(FakeNodeUpdateTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeNodeUpdateTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNodeUpdateTaskList) DeepCopyInto(out *FakeNodeUpdateTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FakeNodeUpdateTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNodeUpdateTaskList.
func (in *FakeNodeUpdateTaskList) DeepCopy() *FakeNodeUpdateTaskList {
	if in == nil {
		return nil
	}
	out := new(FakeNodeUpdateTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeNodeUpdateTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNodeUpdateTaskSpec) DeepCopyInto(out *FakeNodeUpdateTaskSpec) {
	*out = *in
	out.NewMachineSpec = in.NewMachineSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNodeUpdateTaskSpec.
func (in *FakeNodeUpdateTaskSpec) DeepCopy() *FakeNodeUpdateTaskSpec {
	if in == nil {
		return nil
	}
	out := new(FakeNodeUpdateTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNodeUpdateTaskStatus) DeepCopyInto(out *FakeNodeUpdateTaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]apiv1beta1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNodeUpdateTaskStatus.
func (in *FakeNodeUpdateTaskStatus) DeepCopy() *FakeNodeUpdateTaskStatus {
	if in == nil {
		return nil
	}
	out := new(FakeNodeUpdateTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNodeUpdateTaskTemplate) DeepCopyInto(out *FakeNodeUpdateTaskTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNodeUpdateTaskTemplate.
func (in *FakeNodeUpdateTaskTemplate) DeepCopy() *FakeNodeUpdateTaskTemplate {
	if in == nil {
		return nil
	}
	out := new(FakeNodeUpdateTaskTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeNodeUpdateTaskTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNodeUpdateTaskTemplateList) DeepCopyInto(out *FakeNodeUpdateTaskTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FakeNodeUpdateTaskTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNodeUpdateTaskTemplateList.
func (in *FakeNodeUpdateTaskTemplateList) DeepCopy() *FakeNodeUpdateTaskTemplateList {
	if in == nil {
		return nil
	}
	out := new(FakeNodeUpdateTaskTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FakeNodeUpdateTaskTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNodeUpdateTaskTemplateResource) DeepCopyInto(out *FakeNodeUpdateTaskTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNodeUpdateTaskTemplateResource.
func (in *FakeNodeUpdateTaskTemplateResource) DeepCopy() *FakeNodeUpdateTaskTemplateResource {
	if in == nil {
		return nil
	}
	out := new(FakeNodeUpdateTaskTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakeNodeUpdateTaskTemplateSpec) DeepCopyInto(out *FakeNodeUpdateTaskTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakeNodeUpdateTaskTemplateSpec.
func (in *FakeNodeUpdateTaskTemplateSpec) DeepCopy() *FakeNodeUpdateTaskTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(FakeNodeUpdateTaskTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineDeploymentExternalUpdateRequest) DeepCopyInto(out *MachineDeploymentExternalUpdateRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CommonRequest.DeepCopyInto(&out.CommonRequest)
	if in.ClusterRef != nil {
		in, out := &in.ClusterRef, &out.ClusterRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.MachineDeploymentRef != nil {
		in, out := &in.MachineDeploymentRef, &out.MachineDeploymentRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.MachinesRequireUpdate != nil {
		in, out := &in.MachinesRequireUpdate, &out.MachinesRequireUpdate
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	out.NewMachine = in.NewMachine
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineDeploymentExternalUpdateRequest.
func (in *MachineDeploymentExternalUpdateRequest) DeepCopy() *MachineDeploymentExternalUpdateRequest {
	if in == nil {
		return nil
	}
	out := new(MachineDeploymentExternalUpdateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineDeploymentExternalUpdateResponse) DeepCopyInto(out *MachineDeploymentExternalUpdateResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.CommonRetryResponse = in.CommonRetryResponse
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineDeploymentExternalUpdateResponse.
func (in *MachineDeploymentExternalUpdateResponse) DeepCopy() *MachineDeploymentExternalUpdateResponse {
	if in == nil {
		return nil
	}
	out := new(MachineDeploymentExternalUpdateResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineSpec) DeepCopyInto(out *MachineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineSpec.
func (in *MachineSpec) DeepCopy() *MachineSpec {
	if in == nil {
		return nil
	}
	out := new(MachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeUpdateTaskTemplateSpec) DeepCopyInto(out *NodeUpdateTaskTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.InfrastructureRef = in.InfrastructureRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeUpdateTaskTemplateSpec.
func (in *NodeUpdateTaskTemplateSpec) DeepCopy() *NodeUpdateTaskTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(NodeUpdateTaskTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicy) DeepCopyInto(out *UpdatePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicy.
func (in *UpdatePolicy) DeepCopy() *UpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdatePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicyList) DeepCopyInto(out *UpdatePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpdatePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicyList.
func (in *UpdatePolicyList) DeepCopy() *UpdatePolicyList {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdatePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicySpec) DeepCopyInto(out *UpdatePolicySpec) {
	*out = *in
	if in.NodeUpdateTemplateRef != nil {
		in, out := &in.NodeUpdateTemplateRef, &out.NodeUpdateTemplateRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicySpec.
func (in *UpdatePolicySpec) DeepCopy() *UpdatePolicySpec {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicyStatus) DeepCopyInto(out *UpdatePolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicyStatus.
func (in *UpdatePolicyStatus) DeepCopy() *UpdatePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTask) DeepCopyInto(out *UpdateTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTask.
func (in *UpdateTask) DeepCopy() *UpdateTask {
	if in == nil {
		return nil
	}
	out := new(UpdateTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdateTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTaskList) DeepCopyInto(out *UpdateTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpdateTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTaskList.
func (in *UpdateTaskList) DeepCopy() *UpdateTaskList {
	if in == nil {
		return nil
	}
	out := new(UpdateTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpdateTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTaskSpec) DeepCopyInto(out *UpdateTaskSpec) {
	*out = *in
	if in.ClusterRef != nil {
		in, out := &in.ClusterRef, &out.ClusterRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ControlPlaneRef != nil {
		in, out := &in.ControlPlaneRef, &out.ControlPlaneRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.MachineDeploymentRef != nil {
		in, out := &in.MachineDeploymentRef, &out.MachineDeploymentRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.MachinesRequireUpdate != nil {
		in, out := &in.MachinesRequireUpdate, &out.MachinesRequireUpdate
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	out.NewMachineSpec = in.NewMachineSpec
	in.NodeUpdateTemplate.DeepCopyInto(&out.NodeUpdateTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTaskSpec.
func (in *UpdateTaskSpec) DeepCopy() *UpdateTaskSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTaskStatus) DeepCopyInto(out *UpdateTaskStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTaskStatus.
func (in *UpdateTaskStatus) DeepCopy() *UpdateTaskStatus {
	if in == nil {
		return nil
	}
	out := new(UpdateTaskStatus)
	in.DeepCopyInto(out)
	return out
}
